"""Shared column types and mixins.

Every timestamp in RealitySync is timezone-aware. A naive timestamp in a system
whose whole purpose is reconciling *when* things were true is a correctness bug
waiting to happen, so ``DateTime(timezone=True)`` is the only temporal type
used and the database default is ``now()`` in UTC.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

#: Timezone-aware timestamp. Use this, never a bare DateTime.
TimestampTZ = DateTime(timezone=True)


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key generated by PostgreSQL.

    ``gen_random_uuid()`` is built into PostgreSQL 13+, so no extension is
    required. Generating server-side means a row has an id even when it was
    inserted by something other than this application (a migration, a repair
    script), which keeps the key authoritative rather than client-supplied.
    """
    return mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """``created_at`` / ``updated_at``, both server-maintained."""

    created_at: Mapped[datetime] = mapped_column(
        TimestampTZ,
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        TimestampTZ,
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
