"""postgres connector: data sources, streams, observations, sync runs

Creates the Phase 3 ingestion tables. Four are tenant-owned and carry
``organization_id``; ``source_credentials`` deliberately does not — it is
reachable only through its data source, and a second tenant column would be a
second place for the two to disagree.

Decisions worth recording:

1. ``observations`` is unique on ``(stream_id, fingerprint)``. That constraint
   *is* the idempotency mechanism: re-reading an unchanged row produces the
   same fingerprint and the insert becomes a no-op. Doing it with a database
   constraint rather than a read-then-write check means two concurrent syncs
   cannot both pass the check and both insert.

2. ``event_time`` and ``ingested_at`` are separate columns and always will be.
   Substituting ingestion time for event time makes a late-arriving correction
   indistinguishable from a fresh change, which is unrecoverable once done.
   They get separate indexes because ordering by one is a different question
   from ordering by the other.

3. ``source_streams`` has a CHECK tying ``event_time_column`` to
   ``event_time_semantics``: ``ingest_fallback`` is exactly the case with no
   column, every other value requires one. Without it the pair could drift
   into a combination the sync path has no meaning for.

4. ``sync_runs`` has a CHECK that a completed run's counters balance
   (``rows_seen = rows_created + rows_skipped``). A run that reports numbers
   that do not add up has lost track of what it ingested, and quietly wrong
   ingestion counts would undermine everything built on top.

5. ``source_credentials`` stores AES-256-GCM ciphertext with a 12-byte nonce
   (CHECKed) and a key version, so key rotation is a background re-encrypt
   rather than a migration. There is no plaintext column, so no query can
   accidentally select one.

Revision ID: 0003_connector
Revises: 0002_identity_tenancy
Create Date: 2026-08-10

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003_connector"
down_revision: str | None = "0002_identity_tenancy"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'configured'"), nullable=False
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_connection_latency_ms", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('postgresql')", name=op.f("ck_data_sources_kind_valid")),
        sa.CheckConstraint(
            "status IN ('configured', 'connected', 'error', 'disabled')",
            name=op.f("ck_data_sources_status_valid"),
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_data_sources_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_data_sources_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_data_sources_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("organization_id", "name", name="uq_data_sources_organization_name"),
    )
    op.create_table(
        "source_credentials",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "algorithm",
            sa.String(length=32),
            server_default=sa.text("'AES-256-GCM'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "key_version > 0", name=op.f("ck_source_credentials_key_version_positive")
        ),
        sa.CheckConstraint(
            "octet_length(ciphertext) > 0", name=op.f("ck_source_credentials_ciphertext_not_empty")
        ),
        sa.CheckConstraint(
            "octet_length(nonce) = 12", name=op.f("ck_source_credentials_nonce_length")
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_source_credentials_data_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_credentials")),
        sa.UniqueConstraint("data_source_id", name="uq_source_credentials_data_source_id"),
    )
    op.create_table(
        "source_streams",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column("schema_name", sa.String(length=128), nullable=False),
        sa.Column("table_name", sa.String(length=128), nullable=False),
        sa.Column("primary_key_columns", postgresql.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("event_time_column", sa.String(length=128), nullable=True),
        sa.Column(
            "event_time_semantics",
            sa.String(length=32),
            server_default=sa.text("'ingest_fallback'"),
            nullable=False,
        ),
        sa.Column(
            "selected_columns",
            postgresql.ARRAY(sa.String(length=128)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "poll_interval_seconds", sa.Integer(), server_default=sa.text("300"), nullable=False
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(event_time_semantics = 'ingest_fallback' AND event_time_column IS NULL)"
            " OR (event_time_semantics <> 'ingest_fallback' AND event_time_column IS NOT NULL)",
            name=op.f("ck_source_streams_event_time_column_matches_semantics"),
        ),
        sa.CheckConstraint(
            "event_time_semantics IN ('observed', 'recorded', 'ingest_fallback')",
            name=op.f("ck_source_streams_event_time_semantics_valid"),
        ),
        sa.CheckConstraint(
            "array_length(primary_key_columns, 1) >= 1",
            name=op.f("ck_source_streams_primary_key_required"),
        ),
        sa.CheckConstraint(
            "poll_interval_seconds >= 30", name=op.f("ck_source_streams_poll_interval_minimum")
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_source_streams_data_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_source_streams_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_streams")),
        sa.UniqueConstraint(
            "data_source_id",
            "schema_name",
            "table_name",
            name="uq_source_streams_source_schema_table",
        ),
    )
    op.create_index(
        op.f("ix_source_streams_data_source_id"), "source_streams", ["data_source_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_streams_organization_id"),
        "source_streams",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=512), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "entity_mapping_state",
            sa.String(length=16),
            server_default=sa.text("'unmapped'"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_time_semantics", sa.String(length=32), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_mapping_state IN ('unmapped', 'mapped', 'ambiguous')",
            name=op.f("ck_observations_entity_mapping_state_valid"),
        ),
        sa.CheckConstraint(
            "length(btrim(external_id)) > 0", name=op.f("ck_observations_external_id_not_blank")
        ),
        sa.CheckConstraint(
            "length(fingerprint) = 64", name=op.f("ck_observations_fingerprint_length")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_observations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_observations_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["source_streams.id"],
            name=op.f("fk_observations_stream_id_source_streams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint("stream_id", "fingerprint", name="uq_observations_stream_fingerprint"),
    )
    op.create_index(
        "ix_observations_organization_ingested_at",
        "observations",
        ["organization_id", sa.literal_column("ingested_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_observations_source_id_event_time",
        "observations",
        ["source_id", sa.literal_column("event_time DESC")],
        unique=False,
    )
    op.create_index(
        "ix_observations_stream_external_event_time",
        "observations",
        ["stream_id", "external_id", sa.literal_column("event_time DESC")],
        unique=False,
    )
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_skipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("triggered_by_user_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status <> 'completed' OR rows_seen = rows_created + rows_skipped",
            name=op.f("ck_sync_runs_completed_counters_balance"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'skipped')",
            name=op.f("ck_sync_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_sync_runs_completed_after_started"),
        ),
        sa.CheckConstraint(
            "rows_seen >= 0 AND rows_created >= 0 AND rows_skipped >= 0",
            name=op.f("ck_sync_runs_counters_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sync_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_sync_runs_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["source_streams.id"],
            name=op.f("fk_sync_runs_stream_id_source_streams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
            name=op.f("fk_sync_runs_triggered_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
        sa.UniqueConstraint(
            "source_id", "idempotency_key", name="uq_sync_runs_source_idempotency_key"
        ),
    )
    op.create_index(
        "ix_sync_runs_organization_id_started_at",
        "sync_runs",
        ["organization_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_sync_runs_source_id_started_at",
        "sync_runs",
        ["source_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_runs_source_id_started_at", table_name="sync_runs")
    op.drop_index("ix_sync_runs_organization_id_started_at", table_name="sync_runs")
    op.drop_table("sync_runs")
    op.drop_index("ix_observations_stream_external_event_time", table_name="observations")
    op.drop_index("ix_observations_source_id_event_time", table_name="observations")
    op.drop_index("ix_observations_organization_ingested_at", table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_source_streams_organization_id"), table_name="source_streams")
    op.drop_index(op.f("ix_source_streams_data_source_id"), table_name="source_streams")
    op.drop_table("source_streams")
    op.drop_table("source_credentials")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
