"""reality engine: entities, reality states, evidence, conflicts

Phase 4 needs somewhere to put a derived belief and its justification. Five
tables, all tenant-owned:

``entities`` / ``entity_mappings``
    Reality state is per *thing*; observations only know about *rows*. The
    mapping is declared by a human and never inferred - MVP entity resolution
    is deterministic by decision, because an inferred identity that is wrong
    merges two real things irreversibly. Mapping a stream retroactively
    resolves observations it has already produced, so no re-sync is needed and
    no observation is ever rewritten.

``reality_states``
    One row per (entity, attribute): the value, the confidence, the status, and
    ``confidence_breakdown`` - every input to the score, so the number is
    re-derivable by hand rather than merely asserted.

    ``confidence`` is NUMERIC(4,1), not float. A score that renders as 71.0 in
    one place and 70.99999 in another is not reproducible, and reproducibility
    is the entire point of a deterministic engine. A CHECK bounds it to 0-99;
    100 would claim a certainty no finite evidence supports.

``reality_state_evidence``
    Which observations supported, dissented, or were excluded, and the weight
    each carried. This makes "no unsupported assertion" structural: a state
    with no evidence is not writable, and UNKNOWN exists so "we have nothing"
    is expressible without inventing a value.

``conflicts``
    Recorded disagreement, with no write path back into ``reality_states``. If
    conflict resolution could change a value, the state would depend on the
    order conflicts were processed and would stop being reproducible from
    observations alone. ``reality_state_id`` is ON DELETE SET NULL so
    recalculation does not erase conflict history.

    ``score`` is NULLABLE and ``severity`` permits ``'unspecified'``. Detection
    of disagreement is categorical and needs no constants; *grading* it needs
    the conflict-score formula and severity thresholds, which are part of the
    unrecoverable Phase 0 specification. A detected-but-ungraded conflict is
    recorded honestly rather than scored 0, which would read as "harmless".

Nothing here is authoritative. Every row is derived and can be dropped and
recomputed from observations, and must come out identical.

Revision ID: 0004_reality
Revises: 0003_connector
Create Date: 2026-08-10

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_reality"
down_revision: str | None = "0003_connector"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("natural_key", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(entity_type)) > 0", name=op.f("ck_entities_entity_type_not_blank")
        ),
        sa.CheckConstraint(
            "length(btrim(natural_key)) > 0", name=op.f("ck_entities_natural_key_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_entities_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint(
            "organization_id",
            "entity_type",
            "natural_key",
            name="uq_entities_organization_type_natural_key",
        ),
    )
    op.create_table(
        "reality_states",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("attribute", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "confidence_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("selection_reason", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("supporting_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("dissenting_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("source_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "status IN ('confirmed', 'contested', 'provisional', 'stale', 'unknown')",
            name=op.f("ck_reality_states_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 99", name=op.f("ck_reality_states_confidence_range")
        ),
        sa.CheckConstraint(
            "length(btrim(attribute)) > 0", name=op.f("ck_reality_states_attribute_not_blank")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_reality_states_valid_range_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_reality_states_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reality_states_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reality_states")),
        sa.UniqueConstraint("entity_id", "attribute", name="uq_reality_states_entity_attribute"),
    )
    op.create_index(
        op.f("ix_reality_states_entity_id"), "reality_states", ["entity_id"], unique=False
    )
    op.create_index(
        "ix_reality_states_organization_calculated_at",
        "reality_states",
        ["organization_id", sa.literal_column("calculated_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_reality_states_organization_status",
        "reality_states",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "conflicts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("reality_state_id", sa.UUID(), nullable=True),
        sa.Column("attribute", sa.String(length=128), nullable=False),
        sa.Column("conflict_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "conflict_type IN ('value_conflict', 'source_disagreement', 'contested_state')",
            name=op.f("ck_conflicts_conflict_type_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical', 'unspecified')",
            name=op.f("ck_conflicts_severity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'resolved', 'dismissed')",
            name=op.f("ck_conflicts_status_valid"),
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 1)", name=op.f("ck_conflicts_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_conflicts_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_conflicts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reality_state_id"],
            ["reality_states.id"],
            name=op.f("fk_conflicts_reality_state_id_reality_states"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_conflicts_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conflicts")),
        sa.UniqueConstraint(
            "entity_id",
            "attribute",
            "conflict_type",
            "fingerprint",
            name="uq_conflicts_entity_attribute_type_fingerprint",
        ),
    )
    op.create_index(
        "ix_conflicts_entity_id_attribute", "conflicts", ["entity_id", "attribute"], unique=False
    )
    op.create_index(
        "ix_conflicts_organization_detected_at",
        "conflicts",
        ["organization_id", sa.literal_column("detected_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_conflicts_organization_status_severity",
        "conflicts",
        ["organization_id", "status", "severity"],
        unique=False,
    )
    op.create_table(
        "entity_mappings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=512), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(external_id)) > 0", name=op.f("ck_entity_mappings_external_id_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_entity_mappings_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_mappings_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_entity_mappings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["source_streams.id"],
            name=op.f("fk_entity_mappings_stream_id_source_streams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_mappings")),
        sa.UniqueConstraint(
            "stream_id", "external_id", name="uq_entity_mappings_stream_external_id"
        ),
    )
    op.create_index(
        op.f("ix_entity_mappings_entity_id"), "entity_mappings", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_mappings_organization_id"),
        "entity_mappings",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "reality_state_evidence",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("reality_state_id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("observed_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("exclusion_reason", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "role IN ('supporting', 'dissenting', 'excluded')",
            name=op.f("ck_reality_state_evidence_role_valid"),
        ),
        sa.CheckConstraint(
            "weight >= 0", name=op.f("ck_reality_state_evidence_weight_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_reality_state_evidence_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reality_state_evidence_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reality_state_id"],
            ["reality_states.id"],
            name=op.f("fk_reality_state_evidence_reality_state_id_reality_states"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reality_state_evidence")),
        sa.UniqueConstraint(
            "reality_state_id", "observation_id", name="uq_reality_state_evidence_state_observation"
        ),
    )
    op.create_index(
        "ix_reality_state_evidence_observation_id",
        "reality_state_evidence",
        ["observation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reality_state_evidence_organization_id"),
        "reality_state_evidence",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reality_state_evidence_reality_state_id"),
        "reality_state_evidence",
        ["reality_state_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reality_state_evidence_reality_state_id"), table_name="reality_state_evidence"
    )
    op.drop_index(
        op.f("ix_reality_state_evidence_organization_id"), table_name="reality_state_evidence"
    )
    op.drop_index("ix_reality_state_evidence_observation_id", table_name="reality_state_evidence")
    op.drop_table("reality_state_evidence")
    op.drop_index(op.f("ix_entity_mappings_organization_id"), table_name="entity_mappings")
    op.drop_index(op.f("ix_entity_mappings_entity_id"), table_name="entity_mappings")
    op.drop_table("entity_mappings")
    op.drop_index("ix_conflicts_organization_status_severity", table_name="conflicts")
    op.drop_index("ix_conflicts_organization_detected_at", table_name="conflicts")
    op.drop_index("ix_conflicts_entity_id_attribute", table_name="conflicts")
    op.drop_table("conflicts")
    op.drop_index("ix_reality_states_organization_status", table_name="reality_states")
    op.drop_index("ix_reality_states_organization_calculated_at", table_name="reality_states")
    op.drop_index(op.f("ix_reality_states_entity_id"), table_name="reality_states")
    op.drop_table("reality_states")
    op.drop_table("entities")
    # ### end Alembic commands ###
